# Generated by Django 4.1.2 on 2024-12-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_stock_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
